/**
 * Component Catalog REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CatalogItem } from '../model/models';
import { RestErrorMessage } from '../model/models';
import { SortOrder } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CatalogItemsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns the CatalogItem associated to the provided id.
     * Returns the CatalogItem associated to the provided id, unless: &lt;ul&gt; &lt;li&gt; The id is not associated to any CatalogItem. &lt;/li&gt; &lt;li&gt; Or the associated CatalogItem is invalid and can\&#39;t be processed to create a response. &lt;/li&gt; &lt;/ul&gt; 
     * @param id id for the CatalogItem.
     */
    getCatalogItemById(id: string, extraHttpRequestParams?: any): Observable<CatalogItem>;

    /**
     * List of all CatalogItems.
     * Returns a list of all CatalogItems for the given Catalog identified by catalogId.&lt;br/&gt; CatalogItems referenced on a Catalog that are either invalid or non-existent are **excluded** from the response. 
     * @param catalogId id for the Catalog.
     * @param sortByTitle Sort the returned CatalogItems by title, either in ascending or descending order.
     */
    getCatalogItems(catalogId: string, sortByTitle: SortOrder, extraHttpRequestParams?: any): Observable<Array<CatalogItem>>;

}
