/**
 * Component Catalog REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CatalogItemFilter } from '../model/models';
import { RestErrorMessage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CatalogFiltersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List of all CatalogItemFilters.
     * Returns the list of all CatalogItemFilters for the CatalogItems on the Catalog identified by catalogId.&lt;br/&gt; CatalogItemFilters are built based on the contents of the Catalog and its CatalogItems.&lt;br/&gt; Catalog or CatalogItems **with errors** will affect the number and/or contents of the returned CatalogItemFilters. 
     * @param catalogId id for the Catalog.
     */
    getCatalogFilters(catalogId: string, extraHttpRequestParams?: any): Observable<Array<CatalogItemFilter>>;

}
