/**
 * Component Catalog REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FileFormat } from '../model/models';
import { RestErrorMessage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FilesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns the contents of a File.
     * Returns the contents of a File entity associated to the provided id, unless: &lt;ul&gt; &lt;li&gt;The id is not associated to any File.&lt;/li&gt; &lt;li&gt;Or the associated File is invalid (e.g. corrupted) and can\&#39;t be processed to create a response.&lt;/li&gt; &lt;/ul&gt; 
     * @param id id for the File.
     * @param format desired format for the returned File contents, **must** match the actual format.
     */
    getFileById(id: string, format: FileFormat, extraHttpRequestParams?: any): Observable<string>;

}
