/**
 * Component Catalog REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CatalogItemUserActionMessageType = 'success' | 'error';

export const CatalogItemUserActionMessageType = {
    Success: 'success' as CatalogItemUserActionMessageType,
    Error: 'error' as CatalogItemUserActionMessageType
};

