/**
 * Component Catalog REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogItemTag } from './catalog-item-tag';


export interface CatalogItem { 
    id: string;
    path?: string;
    title: string;
    shortDescription: string;
    descriptionFileId?: string;
    imageFileId?: string;
    itemSrc?: string;
    type?: string;
    tags?: Array<CatalogItemTag>;
    authors: Array<string>;
    date: string;
}

