/**
 * Component Catalog REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogItemUserActionParameter } from './catalog-item-user-action-parameter';


export interface CatalogItemUserAction { 
    id?: string;
    displayName?: string;
    url?: string | null;
    triggerMessage?: string | null;
    parameters?: Array<CatalogItemUserActionParameter>;
}

